<a href="https://colab.research.google.com/github/minashahidd/restaurant-business-performance-analysis/blob/main/python/data-exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [5]:
from google.colab import files
upload = files.upload()

Saving menu_items.csv to menu_items.csv
Saving order_details.csv to order_details.csv

In [6]:
orders = pd.read_csv("order_details.csv")
menu = pd.read_csv("menu_items.csv")

In [8]:
orders.head()

   order_details_id  order_id order_date   order_time  item_id
0                 1         1     1/1/23  11:38:36 AM    109.0
1                 2         2     1/1/23  11:57:40 AM    108.0
2                 3         2     1/1/23  11:57:40 AM    124.0
3                 4         2     1/1/23  11:57:40 AM    117.0
4                 5         2     1/1/23  11:57:40 AM    129.0

In [9]:
menu.head()

   menu_item_id      item_name  category  price
0           101      Hamburger  American  12.95
1           102   Cheeseburger  American  13.95
2           103        Hot Dog  American   9.00
3           104  Veggie Burger  American  10.50
4           105   Mac & Cheese  American   7.00

In [10]:
orders.shape

(12234, 5)

In [11]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12234 entries, 0 to 12233
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  12234 non-null  int64
 1   order_id          12234 non-null  int64
 2   order_date        12234 non-null  object
 3   order_time        12234 non-null  object
 4   item_id           12097 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 478.0+ KB

In [12]:
orders.isnull().sum()

order_details_id      0
order_id              0
order_date            0
order_time            0
item_id             137
dtype: int64

In [13]:
menu.isnull().sum()

menu_item_id    0
item_name       0
category        0
price           0
dtype: int64

In [14]:
orders.duplicated().sum()

np.int64(0)

In [15]:
menu.duplicated().sum()

np.int64(0)

In [16]:
orders.describe()

       order_details_id      order_id       item_id
count      12234.000000  12234.000000  12097.000000
mean        6117.500000   2691.927415    115.202282
std         3531.795931   1546.026261      9.387580
min            1.000000      1.000000    101.000000
25%         3059.250000   1351.250000    107.000000
50%         6117.500000   2710.000000    114.000000
75%         9175.750000   4020.000000    123.000000
max        12234.000000   5370.000000    132.000000

In [17]:
menu.describe()

       menu_item_id      price
count     32.000000  32.000000
mean     116.500000  13.285937
std        9.380832   3.858071
min      101.000000   5.000000
25%      108.750000  10.500000
50%      116.500000  13.950000
75%      124.250000  15.750000
max      132.000000  19.950000

In [18]:
menu['category'].unique()

array(['American', 'Asian', 'Mexican', 'Italian'], dtype=object)

In [19]:
menu['price'].unique()

array([12.95, 13.95,  9.  , 10.5 ,  7.  , 16.5 , 14.5 , 17.95, 11.95,
       14.95,  5.  , 15.5 , 19.95, 16.95])

In [20]:
orders.head()

   order_details_id  order_id order_date   order_time  item_id
0                 1         1     1/1/23  11:38:36 AM    109.0
1                 2         2     1/1/23  11:57:40 AM    108.0
2                 3         2     1/1/23  11:57:40 AM    124.0
3                 4         2     1/1/23  11:57:40 AM    117.0
4                 5         2     1/1/23  11:57:40 AM    129.0

In [21]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12234 entries, 0 to 12233
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  12234 non-null  int64
 1   order_id          12234 non-null  int64
 2   order_date        12234 non-null  object
 3   order_time        12234 non-null  object
 4   item_id           12097 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 478.0+ KB

In [22]:
orders.shape

(12234, 5)

In [23]:
orders['order_id'].nunique()

5370

In [24]:
orders[orders['item_id'].isnull()]

       order_details_id  order_id order_date   order_time  item_id
121                 122        50     1/1/23   6:41:01 PM      NaN
297                 298       125     1/2/23   8:31:06 PM      NaN
357                 358       147     1/3/23   2:32:51 PM      NaN
386                 387       161     1/3/23   4:43:46 PM      NaN
469                 470       200     1/3/23  10:24:05 PM      NaN
...                 ...       ...        ...          ...      ...
11716             11717      5149    3/28/23   2:48:50 PM      NaN
11903             11904      5225    3/29/23   5:40:52 PM      NaN
11906             11907      5226    3/29/23   5:43:56 PM      NaN
12021             12022      5281    3/30/23   4:56:04 PM      NaN
12063             12064      5303    3/30/23   9:15:27 PM      NaN

[137 rows x 5 columns]

In [25]:
orders[orders['item_id'].isnull()]['order_id'].nunique()

137

In [26]:
orders['item_id'].nunique()

32

In [27]:
menu.head()

   menu_item_id      item_name  category  price
0           101      Hamburger  American  12.95
1           102   Cheeseburger  American  13.95
2           103        Hot Dog  American   9.00
3           104  Veggie Burger  American  10.50
4           105   Mac & Cheese  American   7.00

In [28]:
menu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   menu_item_id  32 non-null     int64
 1   item_name     32 non-null     object
 2   category      32 non-null     object
 3   price         32 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ KB

In [29]:
menu.isnull().sum()

menu_item_id    0
item_name       0
category        0
price           0
dtype: int64

In [30]:
menu.duplicated().sum()

np.int64(0)